name: hot_desking
description: A new Flutter project.

publish_to: 'none'
version: 1.0.25+25

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  get: ^4.6.1
  page_transition: ^2.0.4
  flutter_screenutil: ^5.1.0
  persistent_bottom_nav_bar:
    path: packages/persistent_bottom_nav_bar
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.13
  date_picker_timeline: ^1.2.3
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.9
  firebase_core: ^1.13.1
  intl: ^0.17.0
  event_bus: ^2.0.0
  flutter_svg: ^1.0.3
  dropdown_search: ^3.0.1
  horizontal_data_table: ^4.0.0
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/1024.png"
  adaptive_icon_background: "#361E55"
  adaptive_icon_foreground: "assets/logo/1024.png"

flutter:

  uses-material-design: true

  assets:
    - assets/common/
    - assets/login/
    - assets/welcome_screen/
    - assets/chairs/
    - assets/level3/
    - assets/rooms/
    - assets/
    - assets/level14/
    - assets/images/
    - assets/background_floor/floor3/
    - assets/background_floor/floor14/
    - assets/table/
    - assets/svg/level3/
    - assets/svg/level14/
    - assets/png/level3/
    - assets/png/level14/
